name: Code Quality

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: PHP Code Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: PHP Syntax Check (Lint)
        run: |
          find . -type f -name "*.php" \
            -not -path "./vendor/*" \
            -not -path "./node_modules/*" \
            -print0 | xargs -0 -n1 -P 4 php -l
